modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Kenny-Hui/NeoJCM/issues"

[[mods]]
modId = "jsblock"
version = "${version}"
displayName = "NeoJCM"
authors = "LX86"
description = "Addon for NeoMTR, providing more railway facilities."
logoFile = "icon.png"

[[dependencies.jsblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.jsblock]]
modId = "architectury"
type = "required"
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.jsblock]]
modId = "mtr"
reason = "This addon requires NeoMTR. (Not MTR 3 nor MTR 4!)"
type = "required"
versionRange = "[300.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "jsblock-common.mixins.json"